#!/bin/sh

# register commit handler
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@regmon[-1]
	add ucitrack regmon
	set ucitrack.@regmon[-1].init=luci-app-regmon
    add_list ucitrack.@luci_statistics[-1].affects=regmon
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
